In [256]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

In [257]:
data = pd.read_csv('./Data/data_imputed_num_features.csv')
display(data.shape)
display(data.head())

(74250, 53)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,train,longitude_imp_normal,longitude_imp_random_choice,latitude_imp_normal,latitude_imp_random_choice,gps_height_imp_normal,gps_height_imp_random_choice,population_imp_normal,population_imp_random_choice,construction_year_imp_normal,construction_year_imp_random_choice,amount_tsh_imp_normal,amount_tsh_imp_random_choice
0,69572,8.699681,2011-03-14,Roman,1390.0,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,4.700480,True,GeoData Consultants Ltd,VWC,Roman,False,1999.0,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,1,34.938093,34.938093,-9.856322,-9.856322,1390.000000,1390.0,4.700480,4.700480,1999.000000,1999.0,8.699681,8.699681
1,8776,5.826890,2013-03-06,Grumeti,1399.0,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,5.638355,NaN,GeoData Consultants Ltd,Other,NaN,True,2010.0,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,1,34.698766,34.698766,-2.147466,-2.147466,1399.000000,1399.0,5.638355,5.638355,2010.000000,2010.0,6.520780,6.908755
2,34310,3.258097,2013-02-25,Lottery Club,686.0,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,5.525453,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009.0,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,1,37.460664,37.460664,-3.821329,-3.821329,686.000000,686.0,5.525453,5.525453,2009.000000,2009.0,3.258097,3.258097
3,67743,5.420290,2013-01-28,Unicef,263.0,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,4.077537,True,GeoData Consultants Ltd,VWC,NaN,True,1986.0,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,1,38.486161,38.486161,-11.155298,-11.155298,263.000000,263.0,4.077537,4.077537,1986.000000,1986.0,6.906485,3.931826
4,19728,5.301670,2011-07-13,Action In A,1167.0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,5.017280,True,GeoData Consultants Ltd,NaN,NaN,True,2000.0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,1,31.130847,31.130847,-1.825359,-1.825359,1240.292552,455.0,2.575311,0.693147,2016.001834,2006.0,2.826742,2.397895

In [258]:
train = data[data["train"] == 1]
test = data[data["train"] == 0]
display(train.shape)
display(test.shape)

(59400, 53)

(14850, 53)

### Balance train data

In [232]:
# Add labels to train data set
labels = pd.read_csv('./Data/training_set_labels.csv')
train = train.merge(labels, on="id")
train.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,train,longitude_imp_normal,longitude_imp_random_choice,latitude_imp_normal,latitude_imp_random_choice,gps_height_imp_normal,gps_height_imp_random_choice,population_imp_normal,population_imp_random_choice,construction_year_imp_normal,construction_year_imp_random_choice,amount_tsh_imp_normal,amount_tsh_imp_random_choice,status_group
0,69572,8.699681,2011-03-14,Roman,1390.0,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,4.700480,True,GeoData Consultants Ltd,VWC,Roman,False,1999.0,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,1,34.938093,34.938093,-9.856322,-9.856322,1390.000000,1390.0,4.700480,4.700480,1999.000000,1999.0,8.699681,8.699681,functional
1,8776,5.826890,2013-03-06,Grumeti,1399.0,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,5.638355,NaN,GeoData Consultants Ltd,Other,NaN,True,2010.0,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,1,34.698766,34.698766,-2.147466,-2.147466,1399.000000,1399.0,5.638355,5.638355,2010.000000,2010.0,6.520780,6.908755,functional
2,34310,3.258097,2013-02-25,Lottery Club,686.0,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,5.525453,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009.0,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,1,37.460664,37.460664,-3.821329,-3.821329,686.000000,686.0,5.525453,5.525453,2009.000000,2009.0,3.258097,3.258097,functional
3,67743,5.420290,2013-01-28,Unicef,263.0,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,4.077537,True,GeoData Consultants Ltd,VWC,NaN,True,1986.0,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,1,38.486161,38.486161,-11.155298,-11.155298,263.000000,263.0,4.077537,4.077537,1986.000000,1986.0,6.906485,3.931826,non functional
4,19728,5.301670,2011-07-13,Action In A,1167.0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,5.017280,True,GeoData Consultants Ltd,NaN,NaN,True,2000.0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,1,31.130847,31.130847,-1.825359,-1.825359,1240.292552,455.0,2.575311,0.693147,2016.001834,2006.0,2.826742,2.397895,functional

In [233]:
# Show distribution of target class instances
train.groupby('status_group').size()

status_group
functional                 32259
functional needs repair     4317
non functional             22824
dtype: int64

In [234]:
# Create new dataframes for each underrepresented target class
needs_repair_df = train.loc[train['status_group'] == 'functional needs repair']
non_functional_df = train.loc[train['status_group'] == 'non functional']

#### Add additional non functional rows to train data set

In [235]:
# Add random rows for equal distribution of ‘non functional' class 
missing_non_functional = len(train.loc[train['status_group'] == 'functional']) - len(non_functional_df)
additional_non_functionals = non_functional_df.sample(n=missing_non_functional, axis=0)
train = pd.concat([train, additional_non_functionals])

In [236]:
# Show distribution of target class instances after balancing 'non functional' target class
train.groupby('status_group').size()

status_group
functional                 32259
functional needs repair     4317
non functional             32259
dtype: int64

#### Add addtional need repair rows to train data set

In [237]:
# Add additional full sets of 'needs repair' target class
missing_need_repairs = len(train.loc[train['status_group'] == 'functional']) - len(needs_repair_df)
for i in range(missing_need_repairs // len(needs_repair_df)):
    train = pd.concat([train, needs_repair_df])

In [238]:
# Show distribution of target class instances after first step of balancing 'needs repair' target class
train.groupby('status_group').size()

status_group
functional                 32259
functional needs repair    30219
non functional             32259
dtype: int64

In [239]:
# Add random rows for equal distribution of ‘needs repair' class 
additional_needs_repairs = needs_repair_df.sample(n=missing_need_repairs % len(needs_repair_df), axis=0)
train = pd.concat([train, additional_needs_repairs])

In [240]:
# Show distribution of target class instances after first step of balancing 'needs repair' target class
train.groupby('status_group').size()

status_group
functional                 32259
functional needs repair    32259
non functional             32259
dtype: int64

#### Save data to preprocessed csv file

In [241]:
train.drop(columns='status_group', axis=1, inplace=True)
data = pd.concat([train, test])
data.to_csv('./Data/data_imputed_num_features_balanced.csv', index=False)

### Group train data

In [247]:
# Show number of unique values in each categorical feature, if this number of unique values is larger than 125
# Show number of last 30% of unique values and number of levels with a frequency of only one
categorical_features = 'funder installer wpt_name basin subvillage region lga ward recorded_by scheme_management scheme_name extraction_type extraction_type_group extraction_type_class management management_group payment payment_type water_quality quality_group quantity quantity_group source source_type source_class waterpoint_type waterpoint_type_group'.split()
features_to_group = dict()
for feature in categorical_features:
    num = train[feature].nunique()
    if num > 125:
        last_30_pct = int(num*0.3)
        print('{}: {}, 30%: {}'.format(feature, num, last_30_pct))
        freq_one_counter = 0
        groups = train.groupby(feature).size()
        for i in range(len(groups)):
            if groups[i] == 1:
                freq_one_counter += 1
        features_to_group[feature] = [last_30_pct, freq_one_counter]
        print('   Levels with frequency of one: {}'.format(freq_one_counter))

funder: 1897, 30%: 569
   Levels with frequency of one: 974
installer: 2145, 30%: 643
   Levels with frequency of one: 1098
wpt_name: 37400, 30%: 11220
   Levels with frequency of one: 32928
subvillage: 19287, 30%: 5786
   Levels with frequency of one: 9424
ward: 2092, 30%: 627
   Levels with frequency of one: 30
scheme_name: 2696, 30%: 808
   Levels with frequency of one: 712

#### Group by aggregating last 30% to 'Others'

In [249]:
for feature, values in features_to_group.items():
    total_levels = train[feature].nunique()
    num_to_replace = values[0]
    print('{} - Total levels: {}; 30%: {}'.format(feature, total_levels, num_to_replace))
    least_common_values = list(train[feature].value_counts().index[-num_to_replace:])
    train[feature] = train.apply(lambda row: 'Others' if row[feature] in least_common_values else row[feature], axis=1)
    print('{} - Total levels after grouping by last 30%: {}'.format(feature, train[feature].nunique()))

funder - Total levels: 1897; 30%: 569
funder - Total levels after grouping by last 30%: 1328
installer - Total levels: 2145; 30%: 643
installer - Total levels after grouping by last 30%: 1503
wpt_name - Total levels: 37400; 30%: 11220
wpt_name - Total levels after grouping by last 30%: 26181
subvillage - Total levels: 19287; 30%: 5786
subvillage - Total levels after grouping by last 30%: 13502
ward - Total levels: 2092; 30%: 627
ward - Total levels after grouping by last 30%: 1466
scheme_name - Total levels: 2696; 30%: 808
scheme_name - Total levels after grouping by last 30%: 1889

In [250]:
data = pd.concat([train, test])
data.to_csv('./Data/data_imputed_num_features_grouped-30-pct.csv', index=False)

#### Group by aggregating each level to 'Others' which only occurs once

In [254]:
for feature, values in features_to_group.items():
    total_levels = train[feature].nunique()
    num_to_replace = values[1]
    print('{} - Total levels: {}; levels with frequency of one: {}'.format(feature, total_levels, num_to_replace))
    least_common_values = list(train[feature].value_counts().index[-num_to_replace:])
    train[feature] = train.apply(lambda row: 'Others' if row[feature] in least_common_values else row[feature], axis=1)
    print('{} - Total levels after grouping by frequency of 1: {}'.format(feature, train[feature].nunique()))

funder - Total levels: 1897; levels with frequency of one: 974
funder - Total levels after grouping by frequency of 1: 923
installer - Total levels: 2145; levels with frequency of one: 1098
installer - Total levels after grouping by frequency of 1: 1048
wpt_name - Total levels: 37400; levels with frequency of one: 32928
wpt_name - Total levels after grouping by frequency of 1: 4473
subvillage - Total levels: 19287; levels with frequency of one: 9424
subvillage - Total levels after grouping by frequency of 1: 9864
ward - Total levels: 2092; levels with frequency of one: 30
ward - Total levels after grouping by frequency of 1: 2063
scheme_name - Total levels: 2696; levels with frequency of one: 712
scheme_name - Total levels after grouping by frequency of 1: 1985

In [255]:
data = pd.concat([train, test])
data.to_csv('./Data/data_imputed_num_features_grouped-freq-one.csv', index=False)

#### Group by aggregating by last 30% or levels with frequency of one - depending on which value of grouped levels is higher

In [259]:
for feature, values in features_to_group.items():
    values_30_pct = values[0]
    values_freq_one = values[1]
    total_levels = train[feature].nunique()
    print('{} - Total levels: {}; 30%: {}, levels with frequency of one: {}'.format(feature, total_levels, values_30_pct, values_freq_one))
    num_to_replace = values_freq_one if values_freq_one > values_30_pct else values_30_pct
    least_common_values = list(train[feature].value_counts().index[-num_to_replace:])
    train[feature] = train.apply(lambda row: 'Others' if row[feature] in least_common_values else row[feature], axis=1)
    print('{} - Number of grouped levels: {}, Total levels after grouping: {}'.format(feature, num_to_replace, train[feature].nunique()))

funder - Total levels: 1897; 30%: 569, levels with frequency of one: 974
funder - Number of grouped levels: 974, Total levels after grouping: 923
installer - Total levels: 2145; 30%: 643, levels with frequency of one: 1098
installer - Number of grouped levels: 1098, Total levels after grouping: 1048
wpt_name - Total levels: 37400; 30%: 11220, levels with frequency of one: 32928
wpt_name - Number of grouped levels: 32928, Total levels after grouping: 4473
subvillage - Total levels: 19287; 30%: 5786, levels with frequency of one: 9424
subvillage - Number of grouped levels: 9424, Total levels after grouping: 9864
ward - Total levels: 2092; 30%: 627, levels with frequency of one: 30
ward - Number of grouped levels: 627, Total levels after grouping: 1466
scheme_name - Total levels: 2696; 30%: 808, levels with frequency of one: 712
scheme_name - Number of grouped levels: 808, Total levels after grouping: 1889

In [260]:
data = pd.concat([train, test])
data.to_csv('./Data/data_imputed_num_features_grouped-mixed.csv', index=False)